name: swipe
description: A Flutter application

publish_to: "none" # Remove or replace if you intend to publish this package.

# The following section is specific to Flutter.
version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  
  # iOS style icons
  cupertino_icons: ^1.0.8

  # Core packages
  dio: ^5.2.1
  provider: ^6.0.5
  connectivity_plus: ^6.1.2
  image_picker: ^1.1.2
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0
  intl: ^0.20.2
  path: ^1.8.2
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.1
  image_cropper: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
